{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "0fcef182-a92c-46cf-94d9-2c4184edba05",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8054/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x27c95b30510>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "import numpy as np\n",
    "from dash import Dash, html, dcc, callback, Output, Input\n",
    "import pandas as pd\n",
    "import plotly.express as px\n",
    "import ssl\n",
    "\n",
    "def create_dataset():\n",
    "    ssl._create_default_https_context = ssl._create_unverified_context\n",
    "    df = pd.read_html('https://en.wikipedia.org/wiki/List_of_FIFA_World_Cup_finals')[3] # cols-> Year\tWinners\tScore\tRunners-up\tVenue\tLocation\tAttendance\tRef.\n",
    "\n",
    "    for col in ['Winners', 'Runners-up', 'Location']:\n",
    "        df[col] = df[col].replace({'West Germany': 'Germany', 'Munich, West Germany': 'Munich, Germany'})\n",
    "\n",
    "    win_counts = df['Winners'].value_counts().reset_index()\n",
    "    win_counts.columns = [\"Country\", \"Wins\"]\n",
    "    return df, win_counts\n",
    "\n",
    "df, winners = create_dataset()\n",
    "\n",
    "\n",
    "app = Dash(__name__)\n",
    "server = app.server\n",
    "\n",
    "app.layout = html.Div([\n",
    "    html.H1(\"FIFA World Cup Dashboard\", style={'textAlign': 'center'}),\n",
    "\n",
    "    html.Div([\n",
    "        html.Div([\n",
    "            html.H3(\"World Cup Year (No selection to see all winners)\"),\n",
    "            dcc.Dropdown(df['Year'].unique(),\n",
    "                id='year-dropdown',\n",
    "\n",
    "            ),\n",
    "            dcc.Graph(id='map')\n",
    "        ], style={'width': '100%', 'display': 'inline-block'}),\n",
    "    ]),\n",
    "\n",
    "    html.Div(\n",
    "        style={'width':'250px'},\n",
    "        children=[\n",
    "            html.H3(\"Countries\"),\n",
    "            dcc.Dropdown(winners[\"Country\"], id='country-dropdown')\n",
    "        ]\n",
    "    ),\n",
    "    \n",
    "    html.Div(\n",
    "        style={'width': '250px'},\n",
    "        children=[\n",
    "            html.H3(\"Number of World Cup titles\"),\n",
    "            dcc.Textarea(\n",
    "                id='numWins-display',\n",
    "                value='',\n",
    "                readOnly=True,\n",
    "                style={\"margin\": \"auto\", 'textAlign':'center'}\n",
    "            )\n",
    "        ]       \n",
    "    ) \n",
    "])\n",
    "\n",
    "@callback(\n",
    "    Output('map', 'figure'),\n",
    "    Input('year-dropdown', 'value')\n",
    ")\n",
    "\n",
    "def update_map(selected_year):\n",
    "    if selected_year is None:\n",
    "        fig = px.choropleth(\n",
    "            winners,\n",
    "            locations = \"Country\",\n",
    "            locationmode='country names',\n",
    "            color=\"Wins\",\n",
    "            hover_name=\"Country\",\n",
    "            hover_data=[\"Wins\"],\n",
    "            title=\"All World Cup Winners\",\n",
    "            projection=\"natural earth\"\n",
    "\n",
    "\n",
    "        )\n",
    "    else:\n",
    "        \n",
    "        data = df[df['Year'] == selected_year].iloc[0]\n",
    "        data = pd.DataFrame({\n",
    "            'Country': [data['Winners'], data['Runners-up']],\n",
    "            'Result': ['Winner', 'Runner-up'],\n",
    "            'Color': ['Winner', 'Runner-up']\n",
    "        })\n",
    "        fig = px.choropleth(\n",
    "                data,\n",
    "                locations = 'Country',\n",
    "                locationmode='country names',\n",
    "                color='Color',\n",
    "                hover_name=\"Country\",\n",
    "                hover_data=[\"Result\"],\n",
    "                title=f\"{selected_year} FIFA World Cup Finals\",\n",
    "                projection=\"natural earth\"\n",
    "    \n",
    "    \n",
    "            )\n",
    "    return fig\n",
    "\n",
    "@callback(\n",
    "    Output('numWins-display', 'value'),\n",
    "    Input('country-dropdown', 'value')  \n",
    ")\n",
    "\n",
    "def update_win(selected_country):\n",
    "    if selected_country is None:\n",
    "        return \"\"\n",
    "    \n",
    "    return str(winners.loc[winners['Country'] == selected_country, 'Wins'].values[0])\n",
    "\n",
    "\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True, port=8054)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
